@baseUrl = http://localhost:3333
@authCookie = auth=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmYmFpemxtcHBpaDFocTdhcHFjejNpdTIiLCJyZXN0YXVyYW50SWQiOiJlcXhhMjI5dDFuemVhcGcxeTJ4bDMxZHcifQ.l9p0DUjiWSrB644a1PVQ1eYHS0Bq_iSxV0X-znGHP_E

###
# @name create_restaurant
POST {{baseUrl}}/restaurants
Content-Type: application/json

{
  "name": "Gabriel",
  "email": "gabriel@example.com",
  "phone": "123456789",
  "restaurantName": "Gabriel's Restaurant"
}

###
# @name authenticate_manager
POST {{baseUrl}}/authenticate
Content-Type: application/json

{
  "email": "admin@admin.com"
}

###
# @name authenticate_from_link
GET {{baseUrl}}/auth-links/authenticate?code=g36c8z1ljxanzeuog5ea2spe&redirect=http%3A%2F%2Flocalhost%3A5173
Content-Type: application/json

###
# @name get_profile
GET {{baseUrl}}/me
Cookie: {{authCookie}}
Content-Type: application/json

###
# @name get_order_details
GET {{baseUrl}}/orders/ajqxrryc2iwo86hbwopn7te7
Cookie: {{authCookie}}
Content-Type: application/json

###
# @name approve_order
PATCH {{baseUrl}}/orders/bipmkf0x2a1u3v5qiudmn1tm/approve
Cookie: {{authCookie}}
Content-Type: application/json

###
# @name cancel_order
PATCH {{baseUrl}}/orders/bipmkf0x2a1u3v5qiudmn1tm/cancel
Cookie: {{authCookie}}
Content-Type: application/json

###
# @name dispatch_order
PATCH {{baseUrl}}/orders/bipmkf0x2a1u3v5qiudmn1tm/dispatch
Cookie: {{authCookie}}
Content-Type: application/json

###
# @name deliver_order
PATCH {{baseUrl}}/orders/bipmkf0x2a1u3v5qiudmn1tm/deliver
Cookie: {{authCookie}}
Content-Type: application/json
